### PR TITLE
Enable persian numbers when using persian langauge

### PR DESCRIPTION
**Pull request by hramezani**
copy changes form [moment fa locale file](https://github.com/moment/moment/blob/develop/locale/fa.js)

### CODE REVIEW

**Comment by alitaheri** [comment]
These unicode characters can sometimes mess up some other thing when copied over. or when editing with a keyboard that inputs ascii numbers. Not everyone would approve this change. I'd suggest making it optional with the documented risk. These characters are mine fields! the better option is using a font with persian glyphs for the ascii number. rather than using unicode code points for them.

Also this is a breaking change.

My suggestion is this:

1. Add an optional parameter to `loadPersian` with the name `useArabicCodePoints` (the big name for documentation purposes) which defaults to false.
2. Use the code points only when the user explicitly asks for them.
3. Document the risks and add a disclaimer (Use at your own risk, blah blah, you've been warned, blah blah, darkside)

This prevents breaking changes and adds the feature everyone's been bragging about.

Thanks for getting it this far :+1:

Although you would still need an approval from @behrang

**Comment by hramezani** [comment]
@alitaheri thanks , i wait for @behrang

**Comment by behrang** [comment]
My main point is that you will not just use Persian digits for dates. What ever solution you choose, you will do it for dates AND numbers. Since you will do it for both of them, you will need a solution for both of them and it is better that the solution be one thing. Either a replacer utility function or a font with substituted digits or something else.

@alitaheri you are the maintainer and it's your call.

**Comment by alitaheri** [comment]
@behrang Thanks 😁 What you say is true. If they are using a font with persian glyphs, then they won't need these changes. However, transforming ascii to unicode is hard, especially if you're working with libraries working with your library. Then those libraries should also provide their own transformations too. A tedious task in essence.

I would approve this work as it's a solution that works. But it shouldn't break existing code.

@hramezani Please make the changes ( both to code and to docs ) and I'll happily merge them 😁 👍

**Comment by hramezani** [comment]
@behrang , @alitaheri thanks. i will do it as soon as possible.

**Comment by hramezani** [comment]
@alitaheri the changes are ready.

**Comment by alitaheri** [comment]
Looks good to me 👍 👍 

@behrang Please have a look too. I'm still not that familiar with the code 😅 😅 

Great job @hramezani 👍

**Comment by behrang** [comment]
I think it would be better to make the first parameter of `loadPersian` an object, not a boolean flag. This way, the flag will be more explicit, and future additions will not change method signature.

Also, naming of the flag is not great, after Persian saying Arabic is ambiguous. My proposal:

`moment.loadPersian({usePersianDigits: true})`

**Comment by hramezani** [comment]
@behrang thanks for your reply, check the changes please

**Comment by behrang** [comment]
Excellent. Thanks. @alitaheri if you're happy too, can you merge it?

**Comment by alitaheri** [comment]
@hramezani Nice commit log 👍 Good job 😁

**Pull request merged**
