### PR TITLE
Adding Persian/Dari and pashto 

### PR DESCRIPTION
**Pull request by mahdiataey**
This is a great and useful for developers to have persain-dari and pashto in their calendars, I added it, please kindly accept it and rebuild it on npm.
Thank you

### CODE REVIEW

**Comment by behrang** [comment]
Great. Thanks.

**Comment by behrang** [comment]
Version 0.10.0 released.

**Comment by mahdiataey** [comment]
Thank you so much!
I want to add 2 more for extend function but I'm not pretty sure about the
usage.
You kindly tell me the extend where they are used. If I understand I will
add it.
Cencerly,
Mahdy Ataey,

**Comment by behrang** [comment]
I don't understand the question. Please explain more.

**Comment by mahdiataey** [comment]
this part:

extend(getPrototypeOf(moment.localeData()),
  { _jMonths: [ 'Farvardin'
              , 'Ordibehesht'
              , 'Khordaad'
              , 'Tir'
              , 'Amordaad'
              , 'Shahrivar'
              , 'Mehr'
              , 'Aabaan'
              , 'Aazar'
              , 'Dey'
              , 'Bahman'
              , 'Esfand'
              ]
  , jMonths: function (m) {
      return this._jMonths[m.jMonth()]
    }

  , _jMonthsShort:  [ 'Far'
                    , 'Ord'
                    , 'Kho'
                    , 'Tir'
                    , 'Amo'
                    , 'Sha'
                    , 'Meh'
                    , 'Aab'
                    , 'Aaz'
                    , 'Dey'
                    , 'Bah'
                    , 'Esf'
                    ]
  ,

**Comment by mahdiataey** [comment]
> I don't understand the question. Please explain more.
this part:

extend(getPrototypeOf(moment.localeData()),
  { _jMonths: [ 'Farvardin'
              , 'Ordibehesht'
              , 'Khordaad'
              , 'Tir'
              , 'Amordaad'
              , 'Shahrivar'
              , 'Mehr'
              , 'Aabaan'
              , 'Aazar'
              , 'Dey'
              , 'Bahman'
              , 'Esfand'
              ]
  , jMonths: function (m) {
      return this._jMonths[m.jMonth()]
    }

  , _jMonthsShort:  [ 'Far'
                    , 'Ord'
                    , 'Kho'
                    , 'Tir'
                    , 'Amo'
                    , 'Sha'
                    , 'Meh'
                    , 'Aab'
                    , 'Aaz'
                    , 'Dey'
                    , 'Bah'
                    , 'Esf'
                    ]
  ,

**Comment by behrang** [comment]
These are the full names and short names (3 letter) of Persian months, in English.

**Comment by mahdiataey** [comment]
Thank you sir for your response
I want to add 2 more interfaces in @types/moment-jalaali but the it does
not merge and fails
kindly help me to adding it in index.dt.ts -->  DefinitelyTyped/index.d.ts
at master · DefinitelyTyped/DefinitelyTyped (github.com)
<https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/moment-jalaali/index.d.ts>
during the npm test all it fails
I want to change like this:
moment-jalaali[types]: add 2 more interfaces and functions in index.d.ts by
mahdiataey · Pull Request #65146 · DefinitelyTyped/DefinitelyTyped
(github.com)
<https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65146/commits/9914412bed2e33e4939ea2a1ce12405916be3c55>

**Comment by behrang** [comment]
I'm not familiar with TypeScript, and can't help here, but maybe @alitaheri can help with this.

**Pull request merged**
