### PR TITLE
adding isSame to jMoment to find out if two moments are in same Jalaali unit

### PR DESCRIPTION
**Pull request by ehsandanesh**
isSame is a function that checks whether two moments are in same Jalaali year, month, ...  depends on a unit that passed on. because start and end of year and months  are different in Jalaali than Gregorian. It needs different method to calculate.

### CODE REVIEW

**Comment by behrang** [comment]
There is no need for this, as if they are the same, then both are on the same month and year in both calendar systems. You just have to use `month` or `year` and not `jMonth` or `jYear`.

**Comment by behrang** [comment]
There is no need for this, as if they are the same, then both are on the same month and year in both calendar systems. You just have to use `month` or `year` and not `jMonth` or `jYear`.

**Comment by ehsandanesh** [comment]
Well, I don't think that they are the same, for example : 1 Bahman is in 21 January and 30 Bahman is in 19 February so GMoment return false as I tested so much that JMoment have to return True for Bahman jalali month because 1 Bahman and 30 Bahman are in same Jalali month.

**Comment by behrang** [comment]
Ok, you are right. Added `isSame` method in version `0.4.0`.

**Pull request closed without merging**
