### PR TITLE
change require to import;

### PR DESCRIPTION
**Pull request by hossein-nasr**
وقتی کد رو به صورت قبلی یعنی با استفاده از
require
استفاده می‌کردیم در بروزر خطا می‌داد که نمی‌تونه تابع
moment.localeData
رو صدا بزنه.
ولی وقتی تبدیل به 
import
کردم درست شد.
ورژن 
moment:1.17.1

### CODE REVIEW

**Comment by behrang** [comment]
Not sure how this is working. What environment are you using it in? Please provide more information.

`import` is an ES6 feature, and is not available everywhere.

**Comment by hoossseinut** [comment]
I used `webpack@2.2.1` and I got this error in the chromium (56.0.2924.76). strangely there was no error when I tested the library with node (v6.10.0).

import is ES6 feature but, this library depends on `momentjs@1.x` which to the best of my knowledge written in ES6 and therefore anyone that want to use this library need to use ES6 compiler.

**Comment by behrang** [comment]
`moment` is probably converted to ES5 at build time to be usable in browser and other environments.

Just changing require to import is not a good way to fix this. Currently there is a `require` function, that is added to source code to make it work in browser (the files in the `builder` directory are concatenated to make the final browser compatible file in `build` directory).

I encourage you to first read it and understand current state, then try to fix problems, such as using it with requirejs or other environments.

**Comment by alitaheri** [comment]
@hoossseinut 
ES6 import used that way is equivalent to `const moment = require('moment').default` Some transpilers are smart enough to put some interoperability logic that bridges commonjs with ES6 modules.

Make sure you don't have any loaders messing with `node_modules` folder, things like babel. They can sometimes place the bridge where they shouldn't and things go boom 😱

**Comment by alitaheri** [comment]
@hossein-nasr Is this still relevant? May I go ahead and close this?

**Comment by hossein-nasr** [comment]
@alitaheri, thanks for your information about `const moment = require('moment').default`. I checked my configuration and I did not find anything missing. the point is, as you said, `const moment` is equal to `require('moment').default` not `require('moment')` and this is exactly the problem that I got in the browser. the `moment` was a variable that has a `default` field and `moment.default`.

**Pull request closed without merging**
