### PR TITLE
Update index.js to work with React Native

### LINKED ISSUE #142: Requiring unknown module "./locale/fa"
Hello, Thanks for this nice library,

I'm using moment-jalaali in my React Native project, I get this error when launch release version of application:
```
com.facebook.react.common.JavascriptException: Requiring unknown module "./locale/fa"., stack:
    d@2:595
    n@2:339
    t@2:262
    vt@642:16755
    Mt@642:17781
    pt@642:16844
    loadPersian@641:8971
    value@306:848
    commitLifeCycles@41:56506
    C@41:70217
    T@41:68596
    y@41:68020
    v@41:67857
    h@41:67136
    c@41:66390
    t@41:73330
    updateContainer@41:73948
    render@41:78797
    exports@283:420
    run@279:615
    runApplication@279:2046
    value@18:3582
    <unknown>@18:1067
    value@18:3009
    value@18:1039
```

I think this error related to https://github.com/moment/moment/issues/3624#issuecomment-335190847

Can you fix it, or give any solution for me ??

### PR DESCRIPTION
**Pull request by mehranabi**
Hello, Related to issue https://github.com/jalaali/moment-jalaali/issues/142:
I fixed this problem.

Closes #142

### CODE REVIEW

**Comment by alitaheri** [comment]
We can't merge this PR, see #138

You should find a solution for that issue first. Thank you

**Comment by MehranAbghari** [comment]
Hello, I think that issue happened because they didn't install `moment` package (by npm).
When you use `require('moment/locale/fa')`, you are using moment module and should be installed.
Do you check it ? Other users that installed `moment` report same issue (#138) ?
I don't have any problem with `require('moment/locale/fa')` !!

**Comment by MehranAbghari** [comment]
As you see in this link: https://momentjs.com/docs/#/i18n/loading-into-browser/
When you are changing the locale, should import it!

**Comment by behrang** [comment]
Moment-jalaali has a `loadPersian` method which has enough locale data for using in Persian context, and as it is used in web context and to minimize dependencies, `locale/fa` is not required. 

More info is needed to decide on this. Can the problem be fixed by just requiring `locale/fa` in the main project?

**Comment by AE0011** [comment]
still i have this error in android 4.2.2 at release mode ( debug mode works correct)
`Requiring unknown module "./locale/fa"`

**Comment by mammad2c** [comment]
hi @mehranabi 
use this code instead of these changes on `index.js` : 

```
import fa from "moment/src/locale/fa";
moment.locale("fa", fa);
moment.loadPersian();
```

the error occurs when using 'fromNow' in `moment-jalaali`. so by above code your error will be fixed.

**Comment by mehranabi** [comment]
Hi @mammad2c ,
Thank you, I'll try this...

**Comment by thg303** [comment]
@mammad2c solution worked for my expo[react-native] code.

**Comment by ramyareye** [comment]
@behrang any chance to merge this ?

**Comment by behrang** [comment]
@alitaheri What do you think?

**Comment by alitaheri** [comment]
@behrang I honestly have no idea. this issue has been raised and solved countless times. and I think the issue is in the way moment handles locales. So, if this is good fix let's do it. I can't test it myself as I'm very busy with other stuff at the moment

**Comment by mammad2c** [comment]
@behrang @alitaheri 
If you add a note in README about how to use `fromNow` in react native, I think there is no need to merge this PR.

**Comment by majid-vaghari** [comment]
> @behrang @alitaheri
> If you add a note in README about how to use `fromNow` in react native, I think there is no need to merge this PR.

Can you provide more info?

**Comment by mammad2c** [comment]
@majid-vaghari 
look at [this](https://github.com/jalaali/moment-jalaali/pull/143#issuecomment-461066010)

**Comment by behrang** [comment]
Readme is updated.

**Comment by majid-vaghari** [comment]
> @majid-vaghari
> look at [this](https://github.com/jalaali/moment-jalaali/pull/143#issuecomment-461066010)

@mammad2c 
Well this increases the complexity of the library. Why don't you just merge this PR so using the library would be easier. I don't understand !

**Comment by behrang** [comment]
The reason is that there is a conflict with another issue. Merging this one, would break another one.

**Pull request closed without merging**
